core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nuvemshop_app.urls")),
    path("", include("user_app.urls")),
    path("", include("dashboard_app.urls")),
]

nuvemshop_app/urls.py
from django.urls import path
from . import views


app_name = "nuvemshop_app"

urlpatterns = [
    path("integracao", views.integracao, name="integracao"),
    path("remover", views.desativar_integracao, name="desativar_integracao"),
]

user_app/urls.py
from django.urls import path
from . import views


app_name = "user_app"

urlpatterns = [
    path("login", views.authenticacao, name="authenticacao"),
    path("deslogar", views.deslogar, name="deslogar"),
    path("registre-se", views.cadastrar_usuario, name="registrar"),
    path("perfil", views.perfil, name="perfil"),
]

templates/pages/index.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CloudStore</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/logos/favicon.png' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
  </head>
  <body>
    <!-- Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed">
      <!-- Sidebar Start -->

      <aside class="left-sidebar">
        <!-- Sidebar scroll -->
        <div class="scroll-sidebar" data-simplebar>
          <div class="d-flex mb-4 align-items-center justify-content-between">
            <a href="index.html" class="text-nowrap logo-img ms-0 ms-md-1"><img src="{% static 'assets/images/logos/dark-logo.svg' %}" width="180" alt="" /></a>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
              <i class="ti ti-x fs-8"></i>
            </div>
          </div>
          <!-- Sidebar navigation -->
          <nav class="sidebar-nav">
            <ul id="sidebarnav" class="mb-4 pb-2">
              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-5"></i>
                <span class="hide-menu">Home</span>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link primary-hover-bg" href="./index.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-primary rounded-3"><i class="ti ti-layout-dashboard fs-7 text-primary"></i></span>
                  <span class="hide-menu ms-2 ps-1">Dashboard</span>
                </a>
              </li>
              <!--                                              Main wrapper
              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-5"></i>
                <span class="hide-menu">UI Componenst</span>
              </li>
                                                            -->
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link warning-hover-bg" href="#" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-warning rounded-3"><i class="ti ti-article fs-7 text-warning"></i></span>
                  <span class="hide-menu ms-2 ps-1">Notificações</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link danger-hover-bg" href="./ui-alerts.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-danger rounded-3"><i class="ti ti-alert-circle fs-7 text-danger"></i></span>
                  <span class="hide-menu ms-2 ps-1">Alerts</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link success-hover-bg" href="./ui-card.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-success rounded-3"><i class="ti ti-cards fs-7 text-success"></i></span>
                  <span class="hide-menu ms-2 ps-1">Card</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link primary-hover-bg" href="./ui-forms.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-primary rounded-3"><i class="ti ti-file-description fs-7 text-primary"></i></span>
                  <span class="hide-menu ms-2 ps-1">Forms</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link indigo-hover-bg" href="{% url 'nuvemshop_app:integracao' %}" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-indigo rounded-3"><i class="ti ti-puzzle fs-7 text-indigo"></i></span>
                  <span class="hide-menu ms-2 ps-1">Integração</span>
                </a>
              </li>
              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-5"></i>
                <span class="hide-menu">Auth</span>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link warning-hover-bg" href="./authentication-login.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-warning rounded-3"><i class="ti ti-login fs-7 text-warning"></i></span>
                  <span class="hide-menu ms-2 ps-1">Login</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link danger-hover-bg" href="./authentication-register.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-danger rounded-3"><i class="ti ti-user-plus fs-7 text-danger"></i></span>
                  <span class="hide-menu ms-2 ps-1">Register</span>
                </a>
              </li>
              <li class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-5"></i>
                <span class="hide-menu">Extra</span>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link success-hover-bg" href="./icon-tabler.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-success rounded-3"><i class="ti ti-mood-happy fs-7 text-success"></i></span>
                  <span class="hide-menu ms-2 ps-1">Icons</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link sidebar-link primary-hover-bg" href="./sample-page.html" aria-expanded="false">
                  <span class="aside-icon p-2 bg-light-primary rounded-3"><i class="ti ti-aperture fs-7 text-primary"></i></span>
                  <span class="hide-menu ms-2 ps-1">Sample Page</span>
                </a>
              </li>
            </ul>
            <div class="pb-3 options text-nowrap">
              <div class="nav-small-cap">
                <i class="ti ti-dots nav-small-cap-icon fs-5"></i>
                <span class="hide-menu">More options</span>
              </div>

              <ul class="sidebar-list">
                <li class="sidebar-list-item">
                  <i class="ti ti-circle text-primary fs-4"></i>
                  <span class="hide-menu ms-2">Applications</span>
                </li>
                <li class="sidebar-list-item">
                  <i class="ti ti-circle text-danger fs-4"></i>
                  <span class="hide-menu ms-2">Form Options</span>
                </li>
                <li class="sidebar-list-item">
                  <i class="ti ti-circle text-warning fs-4"></i>
                  <span class="hide-menu ms-2">Table Variations</span>
                </li>
                <li class="sidebar-list-item">
                  <i class="ti ti-circle text-success fs-4"></i>
                  <span class="hide-menu ms-2">Charts Selection</span>
                </li>
                <li class="sidebar-list-item">
                  <i class="ti ti-circle text-indigo fs-4"></i>
                  <span class="hide-menu ms-2">Widgets</span>
                </li>
              </ul>
            </div>
          </nav>
          <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll -->
      </aside>
      <!-- Sidebar End -->
      <!-- Main wrapper -->
      <div class="body-wrapper">
        <!-- Header Start -->
        <header class="app-header">
          <nav class="navbar navbar-expand-lg navbar-light">
            <ul class="navbar-nav">
              <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)"><i class="ti ti-menu-2"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                  <i class="ti ti-bell-ringing"></i>
                  <div class="notification bg-primary rounded-circle"></div>
                </a>
              </li>
            </ul>
            <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
              <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                <div class="btn btn-primary">
                  {% if user.is_authenticated %}
                    Olá,
                    {{ request.user.profile.nome }}
                  {% endif %}
                </div>
                <li class="nav-item dropdown">
                  <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown" aria-expanded="false"><img src="{% static 'assets/images/profile/user1.jpg' %}" alt="" width="35" height="35" class="rounded-circle" /></a>
                  <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                    <div class="message-body">
                      <a href="{% url 'user_app:perfil' %}" class="d-flex align-items-center gap-2 dropdown-item">
                        <i class="ti ti-user fs-6"></i>
                        <p class="mb-0 fs-3">My Profile</p>
                      </a>
                      <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                        <i class="ti ti-mail fs-6"></i>
                        <p class="mb-0 fs-3">My Account</p>
                      </a>
                      <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                        <i class="ti ti-list-check fs-6"></i>
                        <p class="mb-0 fs-3">My Task</p>
                      </a>
                      <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block shadow-none">Logout</a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        <!-- Header End -->

        <div class="container-fluid">
          <div class="card">
            <div class="card-body">
              {% block TituloConteudoFluido %}
                <h5 class="card-title fw-semibold mb-4">Sample Page</h5>
              {% endblock %}
              {% block ConteudoFluido %}
                <p class="mb-0">This is a sample page</p>
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/sidebarmenu.js' %}"></script>
    <script src="{% static 'assets/js/app.min.js' %}"></script>
    <script src="{% static 'assets/libs/simplebar/dist/simplebar.js' %}"></script>
    <script src="{% static 'assets/libs/apexcharts/dist/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/js/dashboard.js' %}"></script>
    <script src="{% static 'assets/js/formatar_imput.js' %}"></script>
  </body>
</html>