core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nuvemshop_app.urls")),
    path("", include("user_app.urls")),
    path("", include("dashboard_app.urls")),
]

nuvemshop_app/urls.py
from django.urls import path
from . import views


app_name = "nuvemshop_app"

urlpatterns = [
    path("integracao", views.integracao, name="integracao"),
    path("remover", views.desativar_integracao, name="desativar_integracao"),
]

nuvemshop_app/models.py
from django.db import models
from django.contrib.auth.models import User


class LojaIntegrada(models.Model):
    id = models.CharField(max_length=20, primary_key=True)  # ID único da Loja Integrada
    nome = models.CharField(max_length=100)
    whatsapp_phone_number = models.CharField(max_length=20, null=True, blank=True)
    contact_email = models.EmailField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    doc = models.CharField(max_length=14, null=True, blank=True)
    autorization_token = models.CharField(max_length=200)
    usuario = models.OneToOneField(User, related_name="loja", on_delete=models.CASCADE)
    ativa = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.nome


"""class Cliente(models.Model):
    cpf_cnpj = models.CharField(max_length=14)
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self) -> str:
        return self.nome


class Venda(models.Model):
    id_venda = models.CharField(max_length=20, primary_key=True)
    data = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    status_pagamento = models.CharField(max_length=50)
    status_envio = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.cliente.nome
"""

nuvemshop_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import LojaIntegrada
from libs.nuvemshop import NuvemShop
from django.contrib import messages

nuvemshop = NuvemShop()
PARAMETRO_CODE = "code"


def ocultar_email(email):
    # Dividir o email em duas partes: o nome de usuário e o domínio
    usuario, dominio = email.split("@")

    # Determinar o número de caracteres a serem ocultados
    num_ocultar = len(usuario) // 2

    # Substituir os caracteres do nome de usuário por asteriscos
    usuario_oculto = "*" * num_ocultar + usuario[num_ocultar:]

    # Retornar o email oculto
    return usuario_oculto + "@" + dominio


"""# Exemplo de uso:
email = "exemplo@email.com"
email_oculto = ocultar_email(email)
print(email_oculto)  # Saída: ex*****@email.com

"""


@login_required
def integracao(request):
    """
    Página de integração onde o usuário pode autorizar uma loja NuvemShop.
    """

    code = request.GET.get(PARAMETRO_CODE, None)
    lojas = LojaIntegrada.objects.all()
    if code is not None:
        return autorizar(request, code=code)
    else:
        return render(request, "nuvemshop_app/integracao.html", {"nova_loja": lojas})


@login_required
def autorizar(request, code):
    """
    Função para autorizar a loja NuvemShop.
    """

    autorizado = nuvemshop.auth_nuvem_shop(code=code)
    access_token = autorizado.get("access_token")
    user_id = autorizado.get("user_id")
    id_existe = LojaIntegrada.objects.filter(id=user_id).first()
    if id_existe is not None:
        email = ocultar_email(email=id_existe.usuario.email)

        messages.error(request, f"Esta loja já está em uso com outro email {email}")
        return redirect("nuvemshop_app:integracao")

    if access_token and user_id:
        return loja_integrada(request, access_token, user_id)

    return render(request, "nuvemshop_app/integracao.html", {"autorizado": autorizado})


"""@login_required
def loja_integrada(request, access_token, user_id):
 
    usuario = request.user
    lj_integrada = nuvemshop.store_nuvem(code=access_token, store_id=user_id)
    id = lj_integrada.get("id")

    loja_existente = LojaIntegrada.objects.filter(id=id, ativa=False).first()

    if loja_existente:
        return messages.error(request, "Está loja já esta em uso com outro email")
    else:
        nova_loja = LojaIntegrada.objects.create(
            id=id,
            nome=lj_integrada.get("nome"),
            whatsapp_phone_number=lj_integrada.get("whatsapp_phone_number"),
            contact_email=lj_integrada.get("contact_email"),
            email=lj_integrada.get("email"),
            doc=lj_integrada.get("doc"),
            autorization_token=access_token,
            usuario=usuario,
        )
        return render(
            request,
            "nuvemshop_app/integracao.html",
            {"lj_integrada": lj_integrada, "nova_loja": nova_loja},
        )
"""


@login_required
def loja_integrada(request, access_token, user_id):
    """
    Função para lidar com a integração de uma loja NuvemShop.
    """
    usuario = request.user
    lj_integrada = nuvemshop.store_nuvem(code=access_token, store_id=user_id)
    id = lj_integrada.get("id")

    loja_existente = LojaIntegrada.objects.filter(id=id).first()

    if loja_existente:
        if loja_existente.ativa == True:
            messages.error(request, "Esta loja já está integrada")
        else:
            # Integrar a loja
            nova_loja = LojaIntegrada.objects.create(
                id=id,
                nome=lj_integrada.get("nome"),
                whatsapp_phone_number=lj_integrada.get("whatsapp_phone_number"),
                contact_email=lj_integrada.get("contact_email"),
                email=lj_integrada.get("email"),
                doc=lj_integrada.get("doc"),
                autorization_token=access_token,
                usuario=usuario,
            )
            messages.success(request, "Loja integrada com sucesso")
    else:
        # Integrar a loja
        nova_loja = LojaIntegrada.objects.create(
            id=id,
            nome=lj_integrada.get("nome"),
            whatsapp_phone_number=lj_integrada.get("whatsapp_phone_number"),
            contact_email=lj_integrada.get("contact_email"),
            email=lj_integrada.get("email"),
            doc=lj_integrada.get("doc"),
            autorization_token=access_token,
            usuario=usuario,
        )
        messages.success(request, "Loja integrada com sucesso")
    return redirect("nuvemshop_app:integracao")


def desativar_integracao(request):
    loja = get_object_or_404(LojaIntegrada, id=request.user.loja.id)

    # Verifica se o ID da loja na URL corresponde ao ID da loja do usuário
    if int(loja.id) == int(request.user.loja.id):
        loja.delete()
        messages.info(request, "Sua loja foi desinstalada com sucesso")
    else:
        messages.error(request, "Você não tem permissão para desinstalar esta loja")

    return redirect("nuvemshop_app:integracao")

nuvemshop_app/templates/nuvemshop_app/blocos/card-nuvemshop.html
<div class="col-md-4">
  <div class="card">
    <div class="card-header position-relative">
      <div class="position-absolute top--2 end-0">
        {% if user.is_authenticated %}
          {% if user.loja %}
            <div class="bg-success text-white rounded-circle d-flex align-items-center justify-content-center" style="width: 25px; height: 25px;">
              <i class="ti ti-check"></i>
            </div>
          {% endif %}
        {% endif %}
      </div>NuvemShop
    </div>
    <div class="card-body">
      <h5 class="card-title">Configuração Nuvemshop</h5>
      <p class="card-text">Você tem loja na Nuvemshop?</p>
      {% if user.is_authenticated %}
        {% if user.loja %}
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Remover</button>
        {% else %}
          <a href="https://www.tiendanube.com/apps/8619/authorize?state=csrf-code" class="btn btn-primary">Conectar</a>
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>

nuvemshop_app/templates/nuvemshop_app/blocos/card-sgpweb.html
<div class="col-md-4" bis_skin_checked="1">
  <!-- Conteudo fora do card <h5 class="card-title fw-semibold mb-4">NuvemShop</h5> -->
  <div class="card" bis_skin_checked="1">
    <div class="card-header" bis_skin_checked="1">NuvemShop</div>
    <div class="card-body" bis_skin_checked="1">
      <h5 class="card-title">Configuração Nuvemshop</h5>
      <p class="card-text">Você tem loja na Nuvemshop?</p>
      <a href="https://www.tiendanube.com/apps/8619/authorize?state=csrf-code" class="btn btn-primary">Conectar</a>
    </div>
  </div>
</div>

nuvemshop_app/templates/nuvemshop_app/blocos/excluir.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Configuração Nuvemshop</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="fs-5">Você já está integrado a Nuvemshop</div><br />
        <div class="fs-5">deseja realmente remover a integração?</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">NÃO</button>
        <a href="{% url 'nuvemshop_app:desativar_integracao' %}" class="btn btn-danger">SIM</a>
      </div>
    </div>
  </div>
</div>

nuvemshop_app/templates/nuvemshop_app/blocos/perfil.html
<div class="col-md-12">
  <div class="card">
    <div class="card-header position-relative">
      <div class="position-absolute top--2 end-0"></div>Perfil
    </div>

    <div class="card-body">
      <form class="row g-3">
        <div class="col-md-6">
          <label for="inputEmail4" class="form-label">Nome</label>
          <input type="text" class="form-control" id="inputEmail4" value="{{ user.profile.nome }}" />
        </div>
        <div class="col-md-6">
          <label for="inputPassword4" class="form-label">E-mail</label>
          <input type="email" class="form-control disabled" id="inputPassword4" value="{{ user.email }}" disabled />
        </div>
        <div class="col-12">
          <label for="inputAddress" class="form-label">Telefone/Celular</label>
          <input type="tel" class="form-control" id="inputAddress" value="{{ user.profile.whatsapp }}" maxlength="15" />
        </div>
        <div class="col-4">
          <label for="inputAddress2" class="form-label">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" value="{{ user.loja.nome }}" />
        </div>
        <div class="col-8">
          <label for="inputAddress2" class="form-label">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" value="{{ user.loja.email }}" />
        </div>
        <div class="col-md-6">
          <label for="inputCity" class="form-label">City</label>
          <input type="text" class="form-control" id="inputCity" value="{{ user.loja.autorization_token }}" />
        </div>
        <div class="col-md-4">
          <label for="inputState" class="form-label">State</label>
          <select id="inputState" class="form-select">
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
        <div class="col-md-2">
          <label for="inputZip" class="form-label">Zip</label>
          <input type="text" class="form-control" id="inputZip" />
        </div>

        <div class="col-12">
          <button type="submit" class="btn btn-primary">Atualizar</button>
        </div>
      </form>
    </div>
  </div>
</div>

nuvemshop_app/templates/nuvemshop_app/blocos/teste.html
<div class="col-md-4">
  <div class="card">
    <div class="card-header position-relative">
      <div class="position-absolute top--2 end-0">
        <input type="text">
        {% if user.is_authenticated %}
          {% if user.loja %}
            <div class="bg-success text-white rounded-circle d-flex align-items-center justify-content-center" style="width: 25px; height: 25px;">
              <i class="ti ti-check"></i>
            </div>
          {% endif %}
        {% endif %}
      </div>NuvemShop
    </div>
    <div class="card-body">
      <h5 class="card-title">Configuração Nuvemshop</h5>
      <p class="card-text">Você tem loja na Nuvemshop?</p>
      {% if user.is_authenticated %}
        {% if user.loja %}
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Remover</button>
        {% else %}
          <a href="https://www.tiendanube.com/apps/8619/authorize?state=csrf-code" class="btn btn-primary">Conectar</a>
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>