core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nuvemshop_app.urls")),
    path("", include("user_app.urls")),
    path("", include("dashboard_app.urls")),
]

user_app/urls.py
from django.urls import path
from . import views


app_name = "user_app"

urlpatterns = [
    path("login", views.authenticacao, name="authenticacao"),
    path("deslogar", views.deslogar, name="deslogar"),
    path("registre-se", views.cadastrar_usuario, name="registrar"),
    path("perfil", views.perfil, name="perfil"),
]

nuvemshop_app/models.py
from django.db import models
from django.contrib.auth.models import User


class LojaIntegrada(models.Model):
    id = models.CharField(max_length=20, primary_key=True)  # ID único da Loja Integrada
    nome = models.CharField(max_length=100)
    whatsapp_phone_number = models.CharField(max_length=20, null=True, blank=True)
    contact_email = models.EmailField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    doc = models.CharField(max_length=14, null=True, blank=True)
    autorization_token = models.CharField(max_length=200)
    usuario = models.OneToOneField(User, related_name="loja", on_delete=models.CASCADE)
    ativa = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.nome


"""class Cliente(models.Model):
    cpf_cnpj = models.CharField(max_length=14)
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self) -> str:
        return self.nome


class Venda(models.Model):
    id_venda = models.CharField(max_length=20, primary_key=True)
    data = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    status_pagamento = models.CharField(max_length=50)
    status_envio = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.cliente.nome
"""

user_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Usuario(models.Model):
    nome = models.CharField(max_length=125)
    whatsapp = models.CharField(max_length=15)
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)

    def __str__(self) -> str:

        return self.nome

user_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.http import require_POST

from django.contrib.auth.signals import user_logged_out
from django.core.cache import cache
from .models import Usuario

from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def authenticacao(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("nuvemshop_app:integracao")
        else:
            messages.error(request, "Usuário ou senha inválido")
            return render(request, "user_app/login.html")

    else:
        return render(request, "user_app/login.html")


@csrf_exempt
def cadastrar_usuario(request):
    if request.method == "POST":
        nome = request.POST.get("nome").capitalize()
        email = request.POST.get("email")
        senha = request.POST.get("password")
        whatsapp = request.POST.get("whatsapp")

        try:
            user = User.objects.get(email=email)
            messages.error(request, "Já existe um usuário com o mesmo e-mail")
            return render(request, "user_app/login.html")
        except User.DoesNotExist:
            novo_usuario, criado = User.objects.get_or_create(
                username=email, email=email, defaults={"password": senha}
            )
            if criado:
                novo_usuario.set_password(senha)
                novo_usuario.save()
                # nome = nome.capitalize()
                user_perfil = Usuario.objects.create(
                    nome=nome, whatsapp=whatsapp, user=novo_usuario
                )
                user_perfil.save()
                user = authenticate(request, username=email, password=senha)
                if user is not None:
                    login(request, user)
                    return redirect("nuvemshop_app:integracao")
                else:
                    messages.error(request, "Falha ao autenticar usuário")
                    return redirect("user_app:authenticacao")
            else:
                messages.error(request, "Já existe um usuário com o mesmo e-mail")
                return render(request, "user_app/login.html")
    else:
        return render(request, "user_app/registrar.html")


@csrf_exempt
def deslogar(request):
    logout(request)
    return redirect("user_app:authenticacao")


def perfil(request):
    if request.method == "POST":
        nome = request.POST.get("inputNome")
        telefone = request.POST.get("inputTelefone")
        if nome and telefone:
            return atualizar_usuario(request, nome, telefone)
        return render(request, "user_app/blocos/perfil.html")
    return render(request, "user_app/blocos/perfil.html")


def atualizar_usuario(request, nome, telefone):
    # TODO
    ...

user_app/templates/user_app/blocos/alerta.html
{% for messages in messages %}
  <div class="alert alert-success" role="alert">{{ messages }}</div>
{% endfor %}

user_app/templates/user_app/blocos/form-cadastro.html
<form action="{% url 'user_app:registrar' %}" method="POST" autocomplete="off">
  {% load static %}
  {% csrf_token %}
  <div class="mb-3">
    <label for="nome" class="form-label">Nome</label>
    <input type="text" class="form-control" id="nome" aria-describedby="nomeHelp" name="nome" required />
  </div>
  <div class="mb-3">
    <label for="whatsapp" class="form-label">WhatsApp</label>
    <input type="tel" class="form-control" id="id_telefone" aria-describedby="whatsappHelp" name="whatsapp" required />
  </div>
  <div class="mb-3">
    <label for="email" class="form-label">E-mail</label>
    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email" required />
  </div>
  <div class="mb-4">
    <label for="password" class="form-label">Senha</label>
    <input type="password" class="form-control" id="password" name="password" required />
  </div>
  <button type="submit" class="btn btn-primary w-100 fs-4 mb-4">Registrar</button>
  <div class="d-flex align-items-center justify-content-center">
    <p class="fs-4 mb-0 fw-bold">Já tem uma conta?</p>
    <a class="text-primary fw-bold ms-2" href="{% url 'user_app:authenticacao' %}">Entrar</a>
  </div>
</form>
<div>
  <script>
    document.addEventListener('DOMContentLoaded', (event) => {
      function formatField(inputElement, format) {
        if (inputElement !== null) {
          inputElement.addEventListener('input', function () {
            let value = this.value.replace(/\D/g, '') // Remove todos os caracteres não numéricos
            let formattedValue = ''
    
            for (let i = 0; i < format.length && value.length > 0; i++) {
              if (format[i] === '#') {
                formattedValue += value[0]
                value = value.slice(1)
              } else {
                formattedValue += format[i]
              }
            }
    
            this.value = formattedValue
          })
        }
      }
    
      // Usando a função formatField para formatar o campo "cep"
      formatField(document.getElementById('cep'), '#####-####')
    
      // Usando a função formatField para formatar o campo "id_cep"
      formatField(document.querySelector('#id_cep'), '#####-####')
    
      // Usando a função formatField para formatar o campo "id_telefone"
      formatField(document.querySelector('#id_telefone'), '(##) #####-####')
    })
  </script>
</div>

user_app/templates/user_app/blocos/form-login.html
<form action="" method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label for="username" class="form-label">E-mail</label>
    <input type="email" class="form-control" id="username" aria-describedby="emailHelp" name="username" required />
  </div>
  <div class="mb-4">
    <label for="password" class="form-label">Senha</label>
    <input type="password" class="form-control" id="password" name="password" required />
  </div>
  <div class="d-flex align-items-center justify-content-between mb-4">
    <div class="form-check">
      <input class="form-check-input primary" type="checkbox" value="" id="flexCheckChecked" checked />
      <label class="form-check-label text-dark" for="flexCheckChecked">Lembre-se deste dispositivo.</label>
    </div>
    <a class="text-primary fw-bold" href="./index.html">Esqueceu sua senha ?</a>
  </div>
  <button type="submit" class="btn btn-primary w-100 fs-4 mb-4">Sign In</button>

  <div class="d-flex align-items-center justify-content-center">
    <p class="fs-4 mb-0 fw-bold">Novo no CloudStore?</p>
    <a class="text-primary fw-bold ms-2" href="{% url 'user_app:registrar' %}">Create an account</a>
  </div>
</form>

user_app/templates/user_app/blocos/perfil.html
{% extends 'pages/index.html' %}
{% block TituloConteudoFluido %}
  <h5 class="card-title fw-semibold mb-4">Meu Perfil</h5>
{% endblock %}
{% block ConteudoFluido %}
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <form class="row g-3" method="POST">
          {% csrf_token %}
          <div class="col-lg-12">
            <div class="card-header position-relative">
              <h6>Meus Dados</h6>
            </div>
          </div>
          <div class="col-md-2">
            <label for="inputEmail4" class="form-label">Identificador</label>
            <input type="text" class="form-control" id="inputEmail4" value="{{ user.profile.id }}" />
          </div>
          <div class="col-md-4">
            <label for="inputNome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="inputNome" name="inputNome" value="{{ user.profile.nome }}" />
          </div>
          <div class="col-md-6">
            <label for="inputEmail" class="form-label">E-mail</label>
            <input type="email" class="form-control disabled" id="inputEmail" value="{{ user.email }}" disabled />
          </div>
          <div class="col-12">
            <label for="inputTelefone" class="form-label">Telefone/Celular</label>
            <input type="tel" class="form-control" id="inputTelefone" name="inputTelefone" value="{{ user.profile.whatsapp }}" maxlength="15" />
          </div>
          <div class="col-lg-12">
            <div class="card-header position-relative">
              <h6>Dados da minha loja</h6>
            </div>
          </div>
          <div class="col-md-4">
            <label for="inputCpfCnpj" class="form-label">CPF/CNPJ</label>
            <input type="text" class="form-control" id="inputCpfCnpj" value="{{ user.loja.doc }}" />
          </div>
          <div class="col-md-4">
            <label for="inputRazaoSocial" class="form-label">Nome / Razão Social</label>
            <input type="text" class="form-control" id="inputRazaoSocial" value="{{ user.loja.nome }}" />
          </div>
          <div class="col-md-4">
            <label for="inputEmailLoja" class="form-label">E-mail</label>
            <input type="text" class="form-control" id="inputEmailLoja" value="{{ user.loja.email }}" />
          </div>
          <div class="col-md-6">
            <label for="inputToken" class="form-label">Token</label>
            <input type="text" class="form-control" id="inputToken" value="{{ user.loja.autorization_token }}" disabled />
          </div>
          <div class="col-md-4">
            <label for="inputEstado" class="form-label">Estado</label>
            <input type="text" class="form-control" id="inputEstado" value="{{ user.loja.whatsapp_phone_number }}" />
          </div>
          <div class="col-md-2">
            <label for="inputCep" class="form-label">Id Loja</label>
            <input type="text" class="form-control" id="inputCep" value="{{ user.loja.id }}" disabled />
          </div>
          <div class="col-12">
            <button type="submit" class="btn btn-success">Atualizar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}